version: '3'

services:
  mqtt-server:
    container_name: mqtt-server
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - PUID:1883
      - PGID:1883
    networks:
      - cansat_default
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log

networks:
  cansat_default:
    external: true
